### ISSUE TITLE
Access the version from code?

### ISSUE THREAD

**Issue by magnattic** [adrdilauro/angular-ab-tests#1]
I am checking out your awesome project and wondering if there is a way besides the directive to get the version that was chosen?

I have to access it in the code to pass it to the analytics service. Is there a Service or value I can inject?

**Comment by bajere** [comment]
Hi @adrdilauro , Where are you on getting the version string readable in the code? As i'm also in the need for this asap. Could we add it ourselves? Do you have a source branch that we can edit and then produce a new package? Thanks

**Comment by adrdilauro** [comment]
Hi @bajere. Sorry for not doing it before, it's been a very busy period. 

I'll do it tomorrow, don't worry

**Comment by bajere** [comment]
Okay that would be perfect. thanks for the package, works really nicely !

**Comment by adrdilauro** [comment]
Guys, I have just uploaded the new version. 

This is how it works: you can now inject `AbTestsService` as below, and call the function `getVersion`. 
 If you call it without parameters, it gets the chosen version associated to the default scope. If you are running concurrent tests and you have different scopes, you can pass the scope you need as argument.

```
import { Component } from '@angular/core';
import { AbTestsService } from 'angular-ab-tests';

@Component({
  selector: '...',
  templateUrl: '...',
})
export class MyComponent {
  constructor(private abTestsService: AbTestsService) {
    // This retrieves the version associated to default scope
    this.abTestsService.getVersion();
    // This retrieves the version associated to a scope different by the default one,
    // in case you are running multiple tests
    this.abTestsService.getVersion('my-scope');
  }
}
```

Please let me know if you need anything else, and thanks for using my package!
