### ISSUE TITLE
Missing documentation for how to set up experiment with Google Optimize

### ISSUE THREAD

**Issue by builtbyjay** [adrdilauro/angular-ab-tests#13]
Hi there.

I'm trying to figure out how to set up my Google Optimize experiment to work with this package, it seems to be the only thing missing from the documentation!

My A/B test is running on a form and tests a new design (with variation name `variation`) against the current design (variation name `original`). I have installed the module and set up everything correctly on my root module - I can see the `angular-ab-tests-default` cookie being set and my new design is being conditionally displayed with the directive. All good so far.

Now I try to set up my experiment in Google Optimize. The objective is a Google Analytics goal which is essentially a conversion to the next page in the form.

I've set up the activation event, targeted the page in question and have set up audience targeting for the cookie `angular-ab-tests-default` where value is equal to either `original` or `variation`. So how do I set up my variants in Google Optimize, and direct users to the correct one?

ie. users with cookie value `original` see the variant named "Original" and users with cookie value `variation` to see "Variant 1".

I wouldn't make any changes to the variants via the Google Optimize UI, obviously that's being done from within my code. But I do need to have the variation in code+cookie aligned with the variant in Optimize, this is crucial for reporting.

Thanks!

**Comment by adrdilauro** [comment]
Hi @builtbyjay 

Unfortunately I have never set up a test on Google Optimize myself: when I developed the module my main task at work was to implement tests in the code, and then some data analyst would set up the test using a combination of GTM + Google Optimize.

What I do remember, is that our Google Optimize implementation was reading from a custom dimension, set in Universal Analytics via GTM, that contained the chosen version. I have got detailed notes about the UA + GTM setup, I'm pasting below a reply I sent to another user of Angular AB Tests in the past, hope it helps.

As far as I remember, once the custom dimension was set in analytics, it was pretty straightforward to use it to split the data in Google Optimize.

## February mail with instructions about how to setup UA+GTM

> The easiest way to measure the test is to define a new GTM variable, that reads from the cookie you have set, and then pass it to GA as custom dimension. You are then able to do all the analytics you want from inside GA.
>
> Unfortunately I cannot give you screenshots because I don't have a personal GTM account, and the company I am contracting for at the moment doesn't have one. I found this article that explains something similar to what you need to do:
>
> https://www.simoahava.com/analytics/simple-split-test-google-tag-manager/
>
> You have to start reading from the point in which he starts talking about the custom dimension. The difference between what the guy of the article does, and what you need to do, is that you have to feed the custom dimension with the GTM variable. (by the way Simo Ahava's site is really good, I suggest you to read often his articles, he is nearly the only person who writes professionally about analytics for developers).
>
> So, once you have your custom dimension set up, you can fire all the events you need in GA, and measure them by splitting the data with the custom dimension. You'll create your reports this way.
>
> Then, when it's time to take the decision about which version is the winner, you'll need to read your reports. I guess you already have some sort of software to analyse the data: if not, remember that the main thing you need to know is when to stop the test, in order to have consistent data. If you have access to tools like Google Optimize, they are the best for this task. I don't know if at the moment there is a free version of Google Optimize.

**Comment by builtbyjay** [comment]
Hi @adrdilauro - thanks for the quick response!

Ah, ok that makes more sense, I can see how you could use this to set a GTM variable and create a custom dimension within GA, bypassing Optimize completely. I still can't quite see how to bring Optimize in to the mix, and force it to show a particular variant using the custom dimension, perhaps it is done using the `ga('set', 'exp')` function documented here: https://developers.google.com/optimize/devguides/experiments#set-exp-id-and-variation-id

I've decided to backtrack a little bit and use Google Optimize to set a `data-` attribute on the `body` tag for my variant. My application will then attempt to read this attribute value during bootstrap and use that to control which version of the form to show to the user.

It's not perfect, I'm relying on Google Optimize loading and setting this attribute before my Angular component tries to read it - but if I set the experiment activation mode to "page load" and ensure my component has a "default" state if the attribute isn't there, it should be pretty resilient.

Fingers crossed :)
