### ISSUE TITLE
Manually set the version

### ISSUE THREAD

**Issue by herzinger** [adrdilauro/angular-ab-tests#6]
Hi, thanks for the lib, it's really simple and effective, so I like it a lot.

That being said, I would like to avoid at least my authenticated users to see different versions across devices, by making an association with the user's registry in the backend of my application. That would be simple to achieve if I could change the version manually after the authentication process.

I figure this would also be useful in some cases where we would allow the user to toggle between versions themselves, like what Google products usually do (with "go back to old version" type links in Gmail and others).

I intend to tackle this issue myself (and I'll be happy to make a pull request if there's any interest), but any advice would be nice. Is there anything I need to keep in mind to expose some sort of setter method in the service?

**Comment by adrdilauro** [comment]
I think the addition you are proposing should be quite simple btw

**Comment by adrdilauro** [comment]
Hi @herzinger,

This is the change: https://github.com/adrdilauro/angular-ab-tests/commit/22afefa48864d5dd2eeda0a2b9b5153108666ef2

I am re-building the module, updating dependencies and documentation; it will be available in a few hours

**Comment by herzinger** [comment]
Oh, thanks. The project I'm working in moved on from AB tests for the time, so I didn't pursue this yet, but that's exactly what I needed, and I'm sure I'll be using this project soon.
